/* Generated By:JavaCC: Do not edit this line. CparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRUCT = 5;
  /** RegularExpression Id. */
  int DATATYPE = 6;
  /** RegularExpression Id. */
  int RETURNTYPE = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int CONSTANT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"struct\"",
    "<DATATYPE>",
    "<RETURNTYPE>",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<CONSTANT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"};\"",
    "\"*\"",
  };

}
