/* Generated By:JavaCC: Do not edit this line. CparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATATYPE = 5;
  /** RegularExpression Id. */
  int RETURNTYPE = 6;
  /** RegularExpression Id. */
  int LABEL = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int CONSTANT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DATATYPE>",
    "<RETURNTYPE>",
    "<LABEL>",
    "<NUMBER>",
    "<LETTER>",
    "<CONSTANT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
  };

}
