/* Generated By:JavaCC: Do not edit this line. CparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASTERISK = 5;
  /** RegularExpression Id. */
  int OPAREN = 6;
  /** RegularExpression Id. */
  int CPAREN = 7;
  /** RegularExpression Id. */
  int STRUCT = 8;
  /** RegularExpression Id. */
  int DATATYPE = 9;
  /** RegularExpression Id. */
  int RETURNTYPE = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"struct\"",
    "<DATATYPE>",
    "<RETURNTYPE>",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<CONSTANT>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
